# Generated by Django 4.0.1 on 2022-08-19 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationOrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegistertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('F', 'FAMALE'), ('M', 'MALE')], default='M', max_length=1)),
                ('id_card', models.CharField(max_length=30, unique=True)),
                ('passport_number', models.CharField(max_length=30, unique=True)),
                ('country_to_travel', models.CharField(choices=[('C', 'China'), ('P', 'Pakistan'), ('R', 'Russia'), ('I', 'Iran'), ('IN', 'India')], default='C', max_length=100)),
                ('price_of_visa', models.DecimalField(decimal_places=2, default=1500, editable=False, max_digits=12)),
                ('visa_type', models.CharField(choices=[('M', 'Medical'), ('S', 'Student'), ('T', 'Tourist'), ('B', 'Business')], default='B', max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(upload_to='officeinfo/images/')),
                ('passport_image', models.ImageField(upload_to='officeinfo/images/')),
                ('tazkira_image', models.ImageField(upload_to='officeinfo/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=30)),
                ('dob', models.DateField(null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_flights', models.DateTimeField(auto_now=True)),
                ('country_to_flights', models.CharField(max_length=100)),
                ('city_to_flights', models.CharField(max_length=100)),
                ('price_of_tickets', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_visa', models.CharField(choices=[('C', 'China'), ('P', 'Pakistan'), ('R', 'Russia'), ('I', 'Iran'), ('IN', 'India')], default='C', max_length=100)),
                ('price_of_visa', models.DecimalField(decimal_places=2, default=1500, editable=False, max_digits=12)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('types_of_visa', models.CharField(choices=[('M', 'Medical'), ('S', 'Student'), ('T', 'Tourist'), ('B', 'Business')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VisasOutcome',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('place_at', models.DateTimeField(auto_now_add=True)),
                ('visa_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approve'), ('F', 'Failed')], default='P', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officeinfo.customerregistertion')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_order_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officeinfo.applicationorderform')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeOrderHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officeinfo.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickests_booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officeinfo.tickets')),
            ],
        ),
        migrations.AddField(
            model_name='applicationorderform',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officeinfo.customerregistertion'),
        ),
        migrations.AddField(
            model_name='applicationorderform',
            name='employee_order_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officeinfo.employeeorderhistories'),
        ),
        migrations.AddField(
            model_name='applicationorderform',
            name='visa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='officeinfo.visatype'),
        ),
    ]
